In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])
print(A)

[1 2 3]


In [3]:
B = np.array([[9.0,8.0,7.0],[6.0,2.2,4.8]])
print(B)

[[9.  8.  7. ]
 [6.  2.2 4.8]]


In [4]:
# Get Dimension
print(A.ndim)
print(B.ndim)

1
2


In [5]:
# Get Shape
print(A.shape)
print(B.shape)

(3,)
(2, 3)


In [6]:
# Get Type
print(A.dtype)
print(B.dtype)

int32
float64


In [7]:
# Set Data Type of Array
C = np.array([1,2,3,4,5], dtype = 'int16')
print(C.dtype)

int16


In [8]:
# Get Size
print(A.itemsize)
print(B.itemsize)
print(C.itemsize)

4
8
2


In [9]:
# Get Total Size of Array
print(A.size)
print(B.size)
print(C.size)

3
6
5


In [10]:
# Get Total Bytes
print(A.nbytes)
print(B.nbytes)
print(C.nbytes)

12
48
10


In [11]:
# Get a specific element
D = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype = 'int16')
print(D[1,2])
print(D[1,-2])

10
13


In [12]:
# Get a specific row
print(D[0, :])

[1 2 3 4 5 6 7]


In [13]:
# Get a specific column
print(D[:,2])

[ 3 10]


In [14]:
# Get a little more fancy [startindex:endindex:stepsize]
print(D[0, 1:6:2])

[2 4 6]


In [15]:
# Changing Element
D[1,5] = 20
print(D)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [16]:
# Changing Elements of a Row/Column
D[:,2] = [1,2]
print(D)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
# 3D Array
E = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(E)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific Element (work outside in)
print(E[0,1,1])

4


In [19]:
# Replace 
E[:,1,:] = [[9,9],[8,8]]
print(E)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [20]:
# All Zeros Matrix
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# All Zeros Matrix
print(np.ones((4,2,2), dtype = 'int16'))

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [22]:
# Any other number Matrix
print(np.full((2,2), 99, dtype = 'float32'))

[[99. 99.]
 [99. 99.]]


In [23]:
# Any other number Matrix (full-like)
print(np.full_like(D, 4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [24]:
# Random decimal numbers Matrics
print(np.random.rand(4,2))

[[0.24357323 0.11445557]
 [0.48163797 0.17904459]
 [0.72595202 0.39683189]
 [0.73742248 0.41756556]]


In [25]:
# Random decimal numbers Matrics using other Matrics size
print(np.random.random_sample(D.shape))

[[4.22034655e-01 2.59584658e-01 6.12654581e-01 5.13265637e-01
  8.81664329e-01 1.93133706e-02 4.79039885e-03]
 [1.49016694e-04 2.16600838e-01 9.75304502e-01 6.67843822e-01
  2.06192943e-01 5.84842470e-01 6.33411539e-01]]


In [26]:
# Random Integer Matrics
print(np.random.randint(7, size=(3,3)))   # 0 to 7

[[3 6 5]
 [0 6 0]
 [4 1 3]]


In [27]:
# Identity Matrix
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
# Repeat Array
F = np.repeat(A, 3)
print(F)

[1 1 1 2 2 2 3 3 3]


In [29]:
# Repeat 2D Array
G = np.array([[1,2,3]])
print(np.repeat(G, 3, axis = 0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
# Copy arrays
H = A.copy()
H[0] = 100
print(H)
print(A)

[100   2   3]
[1 2 3]


In [31]:
# Arithematics on Arrays
print(A + 2)
print(A * 2)
print(A / 2)
A += 2
print(A)

[3 4 5]
[2 4 6]
[0.5 1.  1.5]
[3 4 5]


In [32]:
# Add two arrays
print(A + H)

[103   6   8]


In [33]:
# Trigonometric
print(np.sin(A))
print(np.cos(A))

[ 0.14112001 -0.7568025  -0.95892427]
[-0.9899925  -0.65364362  0.28366219]


In [34]:
# Matrix Multiplication
I = np.ones((2,3))
J = np.full((3,2), 2)
print(np.matmul(I,J))

[[6. 6.]
 [6. 6.]]


In [35]:
# Matrix Determinent
K = np.identity(3)
print(np.linalg.det(K))

1.0


In [36]:
# Vecrtor Dot Product
print(np.vdot(I,J))

12.0


In [37]:
# Eigen Values and Eigen Vectors of Square Array
print(np.linalg.eig(K))

(array([1., 1., 1.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [38]:
# Trace (Sum of Diagonals) of Array
print(np.trace(K))

3.0


In [39]:
# Rank of Array
L = K.copy()
L[:,2] = 0
print(np.linalg.matrix_rank(L))

2


In [40]:
# Inverse of a Matrix
L[:,2] = 5
print(np.linalg.inv(L))

[[ 1.   0.  -1. ]
 [ 0.   1.  -1. ]
 [ 0.   0.   0.2]]


In [41]:
# Eigen Values of Square Array
print(np.linalg.eigvals(K))

[1. 1. 1.]


In [42]:
# Take Min and Max
M = np.array([[1,2,3],[4,5,6]])
print(np.min(M))
print(np.max(M, axis=1))    # In each row

1
[3 6]


In [43]:
# Sum of Elements
print(np.sum(M))

21


In [44]:
# Reorganize arrays
N = np.array([[1,2,3,4],[5,6,7,8]])
O = N.reshape((4,2))
print(N)
print(O)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
# Vertically Stacking
P = np.array([9,1,9])
print(np.vstack([A,P,A,P,P]))

[[3 4 5]
 [9 1 9]
 [3 4 5]
 [9 1 9]
 [9 1 9]]


In [47]:
# Horizonal Stacking
print(np.hstack([A,P]))

[3 4 5 9 1 9]


In [49]:
print(P[P>3])

[9 9]


In [52]:
print(P[[1,2]])

[1 9]
